# These are supported funding model platforms

github: [lmparppei]
ko_fi: beatApp
liberapay: # Replace with a single Liberapay username
custom: ["https://www.beat-app.fi/support-the-development/"]
custom: ["https://www.paypal.com/donate/?hosted_button_id=TY82JG68NSZMJ"]
